### ISSUE TITLE
i can't import datasetlib

### ISSUE THREAD

**Issue by KirosHailay** [PacktPublishing/Mastering-TensorFlow-1x#2]
there is a directory datasetlib but i can't import it.
thank you.

**Comment by armando-fandango** [comment]
The code relies on datasetslib, that is added as a submodule and available in datasetslib folder. To checkout the code with the submoudles use the --recurse-submoudles switch as follows:

git clone --recurse-submodules git@github.com:armando-fandango/Mastering-TensorFlow.git

**Comment by KirosHailay** [comment]
thank you
