### ISSUE TITLE
Data Link 

### ISSUE THREAD

**Issue by Y-H-Zhao** [PacktPublishing/Mastering-TensorFlow-1x#3]
The link of data in chapter 07 is invalid.

**Comment by sarvesh-packt** [comment]
Hi @Y-H-Zhao,

Will you please provide the link or the Screenshot of that link so that we can check.

Regards,

**Comment by sarvesh-packt** [comment]
Hi @Y-H-Zhao,

Will you please provide the link or the Screenshot of that link so that we can check.

Regards,
